In [1]:
import os

In [2]:
import pandas as pd

In [3]:
os.chdir('C:\\Users\\HP\\OneDrive\\Desktop\\Identification of high-reliability regions of machine learning predictions in materials\\Datasets')

In [4]:
list=os.listdir()

In [5]:
list

['ci3c01684_si_002.txt',
 'ci3c01684_si_003.txt',
 'ci3c01684_si_004.txt',
 'ci3c01684_si_005.txt',
 'ci3c01684_si_006.txt']

In [6]:
df1=pd.read_csv('ci3c01684_si_002.txt')

In [7]:
df1

,id,spacegroup,number_of_total_atoms,percent_atom_al,percent_atom_ga,percent_atom_in,lattice_vector_1_ang,lattice_vector_2_ang,lattice_vector_3_ang,lattice_angle_alpha_degree,lattice_angle_beta_degree,lattice_angle_gamma_degree,Ef,Eg
0,1,33,80.0,0.6250,0.3750,0.0000,9.9523,8.5513,9.1775,90.0026,90.0023,90.0017,0.0680,3.4387
1,2,194,80.0,0.6250,0.3750,0.0000,6.1840,6.1838,23.6287,90.0186,89.9980,120.0025,0.2490,2.9210
2,3,227,40.0,0.8125,0.1875,0.0000,9.7510,5.6595,13.9630,90.9688,91.1228,30.5185,0.1821,2.7438
3,4,167,30.0,0.7500,0.0000,0.2500,5.0036,5.0034,13.5318,89.9888,90.0119,120.0017,0.2172,3.3492
4,5,194,80.0,0.0000,0.6250,0.3750,6.6614,6.6612,24.5813,89.9960,90.0006,119.9893,0.0505,1.3793
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,2396,33,40.0,0.7500,0.2500,0.0000,4.9469,8.5014,9.1298,90.0038,90.0023,90.0015,0.0381,3.7349
2396,2397,167,30.0,0.4167,0.5833,0.0000,4.9566,4.9562,13.4178,89.9938,90.0075,120.0007,0.0670,3.4915
2397,2398,206,80.0,0.4375,0.5625,0.0000,9.2204,9.2200,9.2199,90.0047,90.0046,89.9954,0.0906,3.2750
2398,2399,33,80.0,0.3125,0.1875,0.5000,10.6529,9.0954,9.7210,90.0015,89.9996,90.0004,0.2566,1.3915
2399,2400,206,80.0,0.8750,0.0938,0.0312,9.0648,9.0641,9.0643,90.0027,90.0037,89.9987,0.1135,4.2107

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2400 entries, 0 to 2399
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          2400 non-null   int64
 1   spacegroup                  2400 non-null   int64
 2   number_of_total_atoms       2400 non-null   float64
 3   percent_atom_al             2400 non-null   float64
 4   percent_atom_ga             2400 non-null   float64
 5   percent_atom_in             2400 non-null   float64
 6   lattice_vector_1_ang        2400 non-null   float64
 7   lattice_vector_2_ang        2400 non-null   float64
 8   lattice_vector_3_ang        2400 non-null   float64
 9   lattice_angle_alpha_degree  2400 non-null   float64
 10  lattice_angle_beta_degree   2400 non-null   float64
 11  lattice_angle_gamma_degree  2400 non-null   float64
 12  Ef                          2400 non-null   float64
 13  Eg                          2400 non-null   float64
dtypes: float64(12), int64(2)
memory usage: 262.6 KB

In [9]:
df1.isnull().sum()

id                            0
spacegroup                    0
number_of_total_atoms         0
percent_atom_al               0
percent_atom_ga               0
percent_atom_in               0
lattice_vector_1_ang          0
lattice_vector_2_ang          0
lattice_vector_3_ang          0
lattice_angle_alpha_degree    0
lattice_angle_beta_degree     0
lattice_angle_gamma_degree    0
Ef                            0
Eg                            0
dtype: int64

In [10]:
df2=pd.read_csv('ci3c01684_si_003.txt')

In [11]:
df2

,id,spacegroup,number_of_total_atoms,percent_atom_al,percent_atom_ga,percent_atom_in,lattice_vector_1_ang,lattice_vector_2_ang,lattice_vector_3_ang,lattice_angle_alpha_degree,lattice_angle_beta_degree,lattice_angle_gamma_degree,Ef,Eg
0,1,33,80.0,0.1875,0.4688,0.3438,10.5381,9.0141,9.6361,89.9997,90.0003,90.0006,0.2284,1.3584
1,2,33,80.0,0.7500,0.2500,0.0000,9.8938,8.5014,9.1298,90.0038,90.0023,90.0015,0.0591,3.8005
2,3,167,30.0,0.6667,0.1667,0.1667,4.9811,4.9808,13.4799,89.9900,90.0109,120.0014,0.1763,3.5526
3,4,12,80.0,0.5625,0.4375,0.0000,24.3370,6.0091,5.7620,89.9995,103.8581,90.0002,0.0389,3.0172
4,5,12,80.0,0.1875,0.5000,0.3125,24.6443,6.2906,6.1589,90.0000,104.5929,90.0001,0.1470,1.7354
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,596,12,80.0,0.0000,0.5938,0.4062,24.8145,6.3964,6.2933,90.0002,104.7733,90.0001,0.0054,1.4011
596,597,33,40.0,0.1250,0.0000,0.8750,5.5783,9.4849,10.1107,90.0008,89.9967,90.0004,0.2348,0.8068
597,598,194,80.0,0.0000,0.2500,0.7500,6.9377,6.9372,25.0641,90.0072,89.9880,119.9857,0.1086,0.9004
598,599,33,40.0,0.6250,0.0000,0.3750,5.1841,8.8659,9.4956,90.0041,90.0009,90.0007,0.2582,2.2720
599,600,206,80.0,0.3750,0.3438,0.2812,9.4959,9.4956,9.4956,90.0029,90.0031,89.9969,0.2066,2.1375

In [13]:
df3=pd.read_csv('ci3c01684_si_004.txt')

In [14]:
df3

,Material compositions 1,Material compositions 2,Enorm (eV),E_raw (eV),Site2_MeltingT,Site1_MendeleevNumber,Site1_MiracleRadius,GSestFCClatcnt_max_value,Site2_BCCenergy_pa,Site1_BCCfermi,...,BCCenergy_pa_composition_average,MiracleRadius_min_value,MeltingT_min_value,NUnfilled_max_value,Site2_Group,Site1_CovalentRadii,Site2_NUnfilled,SpecificHeatCapacity_difference,Site1_Electronegativity,BCCenergy_pa_arithmetic_average
0,Ag,Ag,0.000000,1.824450,-0.531814,0.402504,0.263045,-0.626925,1.021337,-1.217816,...,1.386573,0.859808,-0.046109,-1.546561,0.626615,0.690287,-1.036320,-1.057898,0.099471,1.386573
1,Ag,Co,-0.090142,1.734308,0.064051,0.402504,0.263045,-0.626925,-0.248457,-1.217816,...,0.484851,-0.730180,-0.046109,-0.801582,0.116318,0.690287,-0.391288,-0.388610,0.099471,0.484851
2,Ag,Cr,0.259139,2.083589,0.524584,0.402504,0.263045,-0.626925,-1.000991,-1.217816,...,-0.049547,-0.311762,-0.046109,0.315885,-0.649128,0.690287,0.576260,-0.287857,0.099471,-0.049547
3,Ag,Cu,-0.022200,1.802250,-0.394504,0.402504,0.263045,-0.626925,0.746249,-1.217816,...,1.191224,-0.646497,-0.046109,-1.546561,0.626615,0.690287,-1.036320,-0.518150,0.099471,1.191224
4,Ag,Fe,0.317672,2.142122,0.112116,0.402504,0.263045,-0.626925,-0.637552,-1.217816,...,0.208542,-0.730180,-0.046109,-0.429093,-0.138831,0.690287,-0.068772,-0.287857,0.099471,0.208542
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,Zr,Nb,-0.067020,2.576100,1.161729,-1.610722,1.247007,0.428381,-1.176407,-1.115927,...,-1.390625,0.776124,1.441713,1.060864,-0.904276,1.735499,0.898777,-1.011120,-1.538087,-1.390625
404,Zr,Ta,0.153850,2.796970,1.765340,-1.610722,1.247007,0.428381,-1.700431,-1.115927,...,-1.762751,0.943491,1.441713,1.060864,-0.904276,1.735499,0.898777,-0.561330,-1.538087,-1.762751
405,Zr,Ti,0.248110,2.891230,0.257430,-1.610722,1.247007,0.428381,-0.451494,-1.115927,...,-0.875841,0.692440,1.130177,1.060864,-1.159425,1.735499,1.221293,-0.176309,-1.538087,-0.875841
406,Zr,Hf,0.204140,2.847260,0.888986,-1.610722,1.247007,0.428381,-1.081422,-1.115927,...,-1.323173,2.031377,1.441713,1.060864,-1.159425,1.735499,1.221293,-0.561330,-1.538087,-1.323173
407,Zr,Sn,0.248040,2.891160,-1.347640,-1.610722,1.247007,1.651375,0.671125,-1.115927,...,-0.078633,1.780327,-1.262013,1.060864,1.392060,1.735499,-0.068772,-0.877982,-1.538087,-0.078633

In [15]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 408 entries, 0 to 407
Data columns (total 29 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Material compositions 1           408 non-null    object
 1   Material compositions 2           408 non-null    object
 2   Enorm (eV)                        408 non-null    float64
 3   E_raw  (eV)                       408 non-null    float64
 4   Site2_MeltingT                    408 non-null    float64
 5   Site1_MendeleevNumber             408 non-null    float64
 6   Site1_MiracleRadius               408 non-null    float64
 7   GSestFCClatcnt_max_value          408 non-null    float64
 8   Site2_BCCenergy_pa                408 non-null    float64
 9   Site1_BCCfermi                    408 non-null    float64
 10  CovalentRadius_max_value          408 non-null    float64
 11  Site2_Density                     408 non-null    float64
 12  n_ws^third_min_value              408 non-null    float64
 13  Site1_HHIr                        408 non-null    float64
 14  IonicRadii_max_value              408 non-null    float64
 15  BoilingT_max_value                408 non-null    float64
 16  valence_arithmetic_average        408 non-null    float64
 17  Site2_NdUnfilled                  408 non-null    float64
 18  Site1_IonicRadii                  408 non-null    float64
 19  BCCenergy_pa_composition_average  408 non-null    float64
 20  MiracleRadius_min_value           408 non-null    float64
 21  MeltingT_min_value                408 non-null    float64
 22  NUnfilled_max_value               408 non-null    float64
 23  Site2_Group                       408 non-null    float64
 24  Site1_CovalentRadii               408 non-null    float64
 25  Site2_NUnfilled                   408 non-null    float64
 26  SpecificHeatCapacity_difference   408 non-null    float64
 27  Site1_Electronegativity           408 non-null    float64
 28  BCCenergy_pa_arithmetic_average   408 non-null    float64
dtypes: float64(27), object(2)
memory usage: 92.6+ KB

In [16]:
df4=pd.read_csv('ci3c01684_si_005.txt')

In [17]:
df4

,formula,z_mean,z_std,grp_mean,grp_std,row_mean,row_std,x_mean,x_std,av_ionrad_mean,...,rsp_mean,rsp_std,av_rsp_mean,av_rsp_std,gtf,of,rho,Ehull,Ef,Eg
0,LaSiAs3,34.0,13.652839,12.4,4.715930,4.6,1.743560,1.908,0.418301,0.7384,...,1.7490,0.665503,0.87450,0.332751,1.079516,0.818182,5.290,0.011,-0.658,0.000
1,CsAuBr3,47.8,17.417233,12.6,6.248200,4.8,0.979796,2.442,0.841865,1.1058,...,2.1140,1.235048,1.05700,0.617524,0.975033,1.211778,5.131,0.000,-0.901,0.680
2,RbAuBr3,44.2,17.417233,12.6,6.248200,4.6,0.800000,2.448,0.830094,1.0758,...,2.0720,1.161006,1.03600,0.580503,0.920723,1.211778,4.752,0.000,-0.865,0.751
3,CsCaBr3,36.0,11.135529,10.8,7.600000,4.4,0.800000,2.134,1.013817,1.1198,...,2.1820,1.272044,1.09100,0.636022,0.941294,1.291053,3.563,0.000,-1.987,4.404
4,KCaBr3,28.8,7.600000,10.8,7.600000,4.0,0.000000,2.140,1.005903,1.0618,...,2.0580,1.073246,1.02900,0.536623,0.839930,1.291053,3.027,0.001,-1.958,4.595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1448,Y2NiRuO6,19.8,14.918445,12.0,5.272571,3.1,1.374773,2.719,0.923953,1.1041,...,1.3455,1.096324,0.67275,0.548162,0.829557,0.555952,6.187,0.268,-2.370,0.000
1449,Yb2MgTiO6,22.2,24.256133,13.4,5.219195,3.5,2.334524,2.569,1.072925,1.1440,...,1.3260,1.079893,0.66300,0.539947,0.783298,0.679365,7.404,0.101,-3.110,0.000
1450,Zn2BiPO6,20.6,22.481993,15.0,1.549193,2.9,1.300000,2.815,0.779798,1.0905,...,0.9787,0.656751,0.48935,0.328376,0.737251,0.628968,6.034,0.035,-2.141,2.803
1451,In2GaBiS6,30.8,21.683173,15.0,1.341641,3.8,1.077033,2.287,0.364419,0.8955,...,1.4392,0.425801,0.71960,0.212901,0.724014,1.019886,4.779,0.001,-0.927,1.787
1452,Yb2PrDyS6,36.1,24.780839,14.5,3.383785,5.0,2.449490,2.003,0.707362,0.9639,...,1.8494,0.918402,0.92470,0.459201,0.702990,1.244886,5.558,0.135,-2.187,1.258

In [18]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1453 entries, 0 to 1452
Data columns (total 61 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   formula            1453 non-null   object
 1   z_mean             1453 non-null   float64
 2   z_std              1453 non-null   float64
 3   grp_mean           1453 non-null   float64
 4   grp_std            1453 non-null   float64
 5   row_mean           1453 non-null   float64
 6   row_std            1453 non-null   float64
 7   x_mean             1453 non-null   float64
 8   x_std              1453 non-null   float64
 9   av_ionrad_mean     1453 non-null   float64
 10  av_ionrad_std      1453 non-null   float64
 11  atom_rad_mean      1453 non-null   float64
 12  atom_rad_std       1453 non-null   float64
 13  atom_mass_mean     1453 non-null   float64
 14  atom_mass_std      1453 non-null   float64
 15  cal_atom_rad_mean  1453 non-null   float64
 16  cal_atom_rad_std   1453 non-null   float64
 17  cov_rad_mean       1453 non-null   float64
 18  cov_rad_std        1453 non-null   float64
 19  bp_mean            1453 non-null   float64
 20  bp_std             1453 non-null   float64
 21  rho_mean           1453 non-null   float64
 22  rho_std            1453 non-null   float64
 23  mp_mean            1453 non-null   float64
 24  mp_std             1453 non-null   float64
 25  mol_vol_mean       1453 non-null   float64
 26  mol_vol_std        1453 non-null   float64
 27  k_mean             1453 non-null   float64
 28  k_std              1453 non-null   float64
 29  vdw_mean           1453 non-null   float64
 30  vdw_std            1453 non-null   float64
 31  iupac_mean         1453 non-null   float64
 32  iupac_std          1453 non-null   float64
 33  val_mean           1453 non-null   float64
 34  val_std            1453 non-null   float64
 35  heat_fus_mean      1453 non-null   float64
 36  heat_fus_std       1453 non-null   float64
 37  heat_vap_mean      1453 non-null   float64
 38  heat_vap_std       1453 non-null   float64
 39  spec_heat_mean     1453 non-null   float64
 40  spec_heat_std      1453 non-null   float64
 41  ea_mean            1453 non-null   float64
 42  ea_std             1453 non-null   float64
 43  ie_mean            1453 non-null   float64
 44  ie_std             1453 non-null   float64
 45  p_mean             1453 non-null   float64
 46  p_std              1453 non-null   float64
 47  pet_mn_mean        1453 non-null   float64
 48  pet_mn_std         1453 non-null   float64
 49  mn_mean            1453 non-null   float64
 50  mn_std             1453 non-null   float64
 51  rsp_mean           1453 non-null   float64
 52  rsp_std            1453 non-null   float64
 53  av_rsp_mean        1453 non-null   float64
 54  av_rsp_std         1453 non-null   float64
 55  gtf                1453 non-null   float64
 56  of                 1453 non-null   float64
 57  rho                1453 non-null   float64
 58  Ehull              1453 non-null   float64
 59  Ef                 1453 non-null   float64
 60  Eg                 1453 non-null   float64
dtypes: float64(60), object(1)
memory usage: 692.6+ KB

In [19]:
df5=pd.read_csv('ci3c01684_si_006.txt',sep='\s+')

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\HP\AppData\Local\Temp\ipykernel_29676\1721648137.py:1: SyntaxWarning: invalid escape sequence '\s'
  df5=pd.read_csv('ci3c01684_si_006.txt',sep='\s+')

In [20]:
df5

,composition,OQMD_Id,A_atom,B_atom,OQMD_unrelaxed_lattice_parameter,OQMD_relaxed_lattice_parameter
0,Ac2O3,692323,Ac,Ac,5.124096,4.705369
1,AcAgO3,351356,Ac,Ag,4.851243,4.123406
2,AcAgO3,352371,Ag,Ac,4.851243,4.502205
3,AcAlO3,350231,Ac,Al,4.844849,3.858296
4,AcAlO3,352192,Al,Ac,4.844849,4.552232
...,...,...,...,...,...,...
5245,ZrVO3,352914,V,Zr,4.591791,4.104108
5246,ZrWO3,351166,Zr,W,4.623399,3.936494
5247,ZrWO3,352893,W,Zr,4.623399,4.116806
5248,ZrZnO3,352906,Zn,Zr,4.613397,4.107545
5249,ZrZnO3,354373,Zr,Zn,4.613397,3.780264

In [21]:
df1

,id,spacegroup,number_of_total_atoms,percent_atom_al,percent_atom_ga,percent_atom_in,lattice_vector_1_ang,lattice_vector_2_ang,lattice_vector_3_ang,lattice_angle_alpha_degree,lattice_angle_beta_degree,lattice_angle_gamma_degree,Ef,Eg
0,1,33,80.0,0.6250,0.3750,0.0000,9.9523,8.5513,9.1775,90.0026,90.0023,90.0017,0.0680,3.4387
1,2,194,80.0,0.6250,0.3750,0.0000,6.1840,6.1838,23.6287,90.0186,89.9980,120.0025,0.2490,2.9210
2,3,227,40.0,0.8125,0.1875,0.0000,9.7510,5.6595,13.9630,90.9688,91.1228,30.5185,0.1821,2.7438
3,4,167,30.0,0.7500,0.0000,0.2500,5.0036,5.0034,13.5318,89.9888,90.0119,120.0017,0.2172,3.3492
4,5,194,80.0,0.0000,0.6250,0.3750,6.6614,6.6612,24.5813,89.9960,90.0006,119.9893,0.0505,1.3793
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,2396,33,40.0,0.7500,0.2500,0.0000,4.9469,8.5014,9.1298,90.0038,90.0023,90.0015,0.0381,3.7349
2396,2397,167,30.0,0.4167,0.5833,0.0000,4.9566,4.9562,13.4178,89.9938,90.0075,120.0007,0.0670,3.4915
2397,2398,206,80.0,0.4375,0.5625,0.0000,9.2204,9.2200,9.2199,90.0047,90.0046,89.9954,0.0906,3.2750
2398,2399,33,80.0,0.3125,0.1875,0.5000,10.6529,9.0954,9.7210,90.0015,89.9996,90.0004,0.2566,1.3915
2399,2400,206,80.0,0.8750,0.0938,0.0312,9.0648,9.0641,9.0643,90.0027,90.0037,89.9987,0.1135,4.2107